# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72ddea91c6e0761f0dbe5899c15a1ee97a2a8f7f235d2055a746edf1f674848351e03b2d27a47bfb255bf3549d332528e6c633cfa7ccd57aedbf16858972736f

test:
  secret_key_base: 9895ca1361013d44de851594b5112f0827aa336ba9da5d4bea8dbcc2aeba755686214d2e6003219aa826e74516450e2681807ad98527cc20914f0cb30220da8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
